INSERT INTO `@derived_project.product_gl.finance_gl_pc_detail`
  SELECT
  CAST('@execution_date' AS DATETIME) AS dlh_batch_ts,
    DATETIME(TIMESTAMP(FORMAT_DATETIME("%Y-%m-%d %H:%M:%S",CURRENT_DATETIME("America/Toronto")))) AS dlh_process_ts,
      sr_trans_staging.policy_account_number,
      sr_trans_staging.policy_number,
      sr_trans_staging.policy_period_start_date,
      sr_trans_staging.policy_period_end_date,
      sr_trans_staging.policy_period_public_id,
      sr_trans_staging.edit_effective_date,
      sr_trans_staging.job_close_date,
      sr_trans_staging.accounting_date,
      sr_trans_staging.uw_company_code,
      sr_trans_staging.branch_number,
      sr_trans_staging.producer_code_of_record_code,
      sr_trans_staging.job_subtype,
      sr_trans_staging.financial_activity_type,
      sr_trans_staging.payment_plan_name,
      sr_trans_staging.product_code,
      sr_trans_staging.product_type,
      sr_trans_staging.product_desc,
      sr_trans_staging.coverable_province,
      sr_trans_staging.coverage_pattern_code,
      sr_trans_staging.class_of_business_code,
      sr_trans_staging.amount_category,
      sr_trans_staging.amount_sub_category,
      sr_trans_staging.amount_type,
      sr_trans_staging.accounting_entry_type,
      sr_trans_staging.gl_account_number,
      sr_trans_staging.actual_term_amount_amt,
      sr_trans_staging.actual_amount_amt,
      sr_trans_staging.gl_amount_amt,
      sr_trans_staging.tax_rate,
      sr_trans_staging.dpae_rate,
      sr_trans_staging.risk_public_id,
      sr_trans_staging.model_number,
      sr_trans_staging.term_number,
      sr_trans_staging.cost_public_id,
      sr_trans_staging.cost_fixed_id,
      sr_trans_staging.coverage_pattern_code,
      sr_trans_staging.external_lob_indicator,
      sr_trans_staging.agnt_inspector,
      sr_trans_staging.substandard_vehicle,
      sr_trans_staging.risk_type,
      sr_trans_staging.brk_num,
      sr_trans_staging.old_uw_company,
      sr_trans_staging.billing_method,
      sr_trans_staging.commission_rate,
      sr_trans_staging.agnt_branch_number,
      sr_trans_staging.vehicle_type,
      'Short rate' AS job_source,
      CAST(format_datetime('%Y-%m-%d %H:%M:%S', timestamp_seconds(unix_seconds(current_timestamp()))) AS DATETIME)AS processed_date,
      '' AS expired,
      extract(YEAR from CAST(sr_trans_staging.accounting_date as DATETIME)) AS acc_year,
      extract(MONTH from CAST(sr_trans_staging.accounting_date as DATETIME)) AS acc_month,
      extract(DAY from CAST(sr_trans_staging.accounting_date as DATETIME)) AS acc_day
    FROM
      `@derived_project.product_gl.sr_trans_staging` sr_trans_staging
;
